const cardInfo = [
  {
    image: "https://i.ibb.co/Tqg8762/whats-app.jpg",
    title: "Todolist",
    text: "Starting React ",
    route: "https://linked-in-with-react-js-unique-project.vercel.app/chat",
  },
  {
    image:
      "https://www.webwise.ie/wp-content/uploads/2015/01/WhatsApp-header-1024x500.jpg",
    title: "What's App Clone with React JS",
    text: "Create Chat",
    route: " https://whatsapp-clone-ten-cyan.vercel.app/",
  },
  {
    image: "https://i.ytimg.com/vi/8QBYrKhqgFI/maxresdefault.jpg",
    title: "Todolist",
    text: "Starting React  ",
    route: "https://linked-in-with-react-js-unique-project.vercel.app/chat",
  },
  {
    image: "https://i.ytimg.com/vi/8QBYrKhqgFI/maxresdefault.jpg",
    title: "Todolist",
    text: "Starting React  ",
    route: "https://linked-in-with-react-js-unique-project.vercel.app/chat",
  },
  {
    image: "https://i.ytimg.com/vi/8QBYrKhqgFI/maxresdefault.jpg",
    title: "Todolist",
    text: "Starting React  ",
    route: "https://linked-in-with-react-js-unique-project.vercel.app/chat",
  },
  {
    image: "https://i.ytimg.com/vi/8QBYrKhqgFI/maxresdefault.jpg",
    title: "Todolist",
    text: "Starting React  ",
    route: "https://linked-in-with-react-js-unique-project.vercel.app/chat",
  },
  {
    image: "https://i.ytimg.com/vi/8QBYrKhqgFI/maxresdefault.jpg",
    title: "Todolist",
    text: "Starting React  ",
  },
  {
    image: "https://i.ytimg.com/vi/8QBYrKhqgFI/maxresdefault.jpg",
    title: "Todolist",
    text: "Starting React  ",
  },
];
export default cardInfo